import { DataTypes, Model, ModelAttributes, Sequelize } from 'sequelize'
import { AutoGeneratedAttrs } from './utils'

export interface GameDataAttrs extends AutoGeneratedAttrs {
  json: Record<string, unknown>
}
export type GameDataAttrsOnlyDefine = Omit<
  GameDataAttrs,
  keyof AutoGeneratedAttrs
>
export type GameDataCreateAttrs = GameDataAttrsOnlyDefine

interface GameDataModel
  extends Model<GameDataAttrs, GameDataCreateAttrs>,
    GameDataAttrs {}

export function defineGameDataModel(sequelize: Sequelize) {
  const attrs: ModelAttributes<GameDataModel, GameDataAttrsOnlyDefine> = {
    json: DataTypes.JSON,
  }
  const modelCtor = class GameData extends sequelize.define<
    GameDataModel,
    GameDataAttrsOnlyDefine
  >('GameData', attrs) {}

  modelCtor.init(attrs as ModelAttributes<GameDataModel, GameDataAttrs>, {
    modelName: modelCtor.name,
    sequelize,
  })

  return modelCtor
}
